server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    ssl_reject_handshake on;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name api.usetably.org;

    ssl_certificate /etc/pki/tls/certs/tably-cloudflare-origin.pem;
    ssl_certificate_key /etc/pki/tls/private/tably-cloudflare-origin.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:TablyTLS:10m;
    ssl_session_timeout 10m;

    include conf.d/elasticbeanstalk/*.conf;
}
